@startuml containers
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
AddRelTag("async", $lineStyle = DashedLine())
SHOW_PERSON_PORTRAIT()

title "Codeflix: Full Cycle course practical project"
Person(catalog_admin, "Video catalog administrator", "Manages catalog videos and their categories")
Person(subscribers_admin, "Subscribers administrator", "Manages system subscribers and subscription plans")
Person(subscriber, "Platform subscriber", "Subscribes to the platform to access the videos")

System_Boundary(gateway, "Codeflix") {
    Container(frontend_catalog_admin, "Frontend: Video Catalog Admin", "React", "SPA that manages videos, including categories and genres")
    Container(backend_catalog_admin, "Backend: Video Catalog Admin", "Any language", "Manages the video catalog, including categories and genres")
    Container(backend_catalog_admin_database, "Video Catalog Admin database", "MySQL", "Stores video catalog data")
    Rel(frontend_catalog_admin, backend_catalog_admin, "Interacts with via", "HTTPS/JSON")
    Rel(backend_catalog_admin, backend_catalog_admin_database, "Interacts with using", "TCP")

    Container(encoder, "Video encoder", "Go", "Encodes videos to MPEG-DASH")
    Container(bucket_videos, "Encoded videos storage bucket", "GCP")
    Container(bucket_videos_raw, "Raw videos storage bucket", "GCP")
    Rel(encoder, bucket_videos, "Uploads the converted video via", "HTTPS")
    Rel(encoder, bucket_videos_raw, "Downloads the raw video via", "HTTPS")
    Rel(backend_catalog_admin, bucket_videos_raw, "Uploads the raw video via", "HTTPS")

    Rel(encoder, backend_catalog_admin, "Consumes newly created video data via", "RabbitMQ queue videos.new", $tags = "async")
    Rel(encoder, backend_catalog_admin, "Publishes that the video was converted via", "RabbitMQ queue videos.converted", $tags = "async")
    Rel(backend_catalog_admin, encoder, "Consumes converted video data via", "RabbitMQ queue videos.converted", $tags = "async")
    Rel(backend_catalog_admin, encoder, "Publishes that a new video was sent to the raw bucket via", "RabbitMQ queue videos.new", $tags = "async")

    Container(frontend_catalog, "Video catalog frontend", "React", "Provides catalog browsing and video playback to subscribers")
    Container(api_catalog, "Video Catalog API", "Any language", "Provides endpoints for catalog browsing and video playback")
    Container(elasticsearch_api_catalog, "Catalog API database", "Elasticsearch", "Stores videos, genres, cast members and categories")
    Container(apache_kafka, "Apache Kafka", "Message broker", "Stores and serves data coming from Kafka Connect")
    Container(kafka_connect, "Kafka Connect", "Data integration", "Catalog data replication service")
    Rel(api_catalog, elasticsearch_api_catalog, "Interacts with via", "HTTPS/JSON")
    Rel(kafka_connect, elasticsearch_api_catalog, "Sends video catalog data via", "Elasticsearch sink", $tags = "async")
    Rel(kafka_connect, backend_catalog_admin_database, "Copies data using connector", "Debezium MySQL", $tags = "async")
    Rel(kafka_connect, apache_kafka, "Interacts with via", "Kafka protocol", $tags = "async")

    Container(subscription, "Subscriptions", "Any language", "Manages subscriber plans and subscriptions")
    Container(subscription_postgres, "Subscriptions database", "Postgres", "Stores subscribers and their plans")
    Rel(subscription, subscription_postgres, "Interacts with via", "Postgres protocol")

    Container(keycloak, "Keycloak", "Identity service", "Authenticates every platform user")

    Rel(catalog_admin, frontend_catalog_admin, "Interacts with via", "HTTPS")

    Rel(subscriber, subscription, "Interacts with via", "HTTPS")
    Rel(subscriber, keycloak, "Interacts with via", "HTTPS")
    Rel(subscription, keycloak, "Interacts with via", "HTTPS")

    Rel(frontend_catalog_admin, keycloak, "Authenticates with", "HTTPS")

    Rel(subscriber, frontend_catalog, "Interacts with via", "HTTPS")
    Rel(frontend_catalog, api_catalog, "Interacts with via", "HTTPS/JSON")

    Rel(subscribers_admin, subscription, "Interacts with", "HTTPS")
}
@enduml
